# Homework Assignment 2

You will be analyzing an xyz file for water (water.xyz) and measuring the distances between all the atoms in the molecule.  The file is located in the data folder of your workshop materials. The output of your code should look like this.

```
O to O : 0.0
O to H1 : 0.969
O to H2 : 0.969
H1 to O : 0.969
H1 to H1 : 0.0
H1 to H2 : 1.527
H2 to O : 0.969
H2 to H1 : 1.527
H2 to H2 : 0.0
```
To do this you will need to use the distance formula.

$$distance = \sqrt{(x_1 - x_2)^2 + (y_1 - y_2)^2 + (z_1 - z_2)^2}$$

As you can see that you will need to square stuff and take the square root.  To take the square root, you will use a function from numpy, `numpy.sqrt()`.  To square something, use `**` notation.  As in, `3**2 = 9` is $3^2 =9$.

In [1]:
pwd

'/Users/fridasaenz/Desktop/cms-workshop'

In [7]:
import os
import numpy

In [10]:
file_location = os.path.join('data','water.xyz')
print(file_location)
xyz_file = numpy.genfromtxt(fname=file_location, dtype='unicode', skip_header=2)
print(xyz_file)

data/water.xyz
[['O' '0.000000' '-0.007156' '0.965491']
 ['H1' '-0.000000' '0.001486' '-0.003471']
 ['H2' '0.000000' '0.931026' '1.207929']]


In [13]:
symbols = xyz_file[:,0]
coordinates = xyz_file[:,1:]
coordinates = coordinates.astype(float)
print(symbols)

['O' 'H1' 'H2']


In [14]:
print(coordinates)

[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]


In [22]:
num_atoms = len(symbols)

for num1 in range(0,num_atoms):
     for num2 in range(0, num_atoms):
        x_distance = coordinates[num1,0] - coordinates[num2,0]
        y_distance = coordinates[num1,1] - coordinates[num2,1]
        z_distance = coordinates[num1,2] - coordinates[num2,2]
        distance = numpy.sqrt(x_distance**2 + y_distance**2 + z_distance**2)
        print(F'{symbols[num1]} to {symbols[num2]} : {distance: .3f}')

O to O :  0.000
O to H1 :  0.969
O to H2 :  0.969
H1 to O :  0.969
H1 to H1 :  0.000
H1 to H2 :  1.527
H2 to O :  0.969
H2 to H1 :  1.527
H2 to H2 :  0.000


In [27]:
# Modify my code to only print atoms that are actually bonded
# Rule: Distance between atoms is less than 1.5 angstoms 

num_atoms = len(symbols)

for num1 in range(0,num_atoms):
     for num2 in range(0, num_atoms):
        #print(num1,num2)
        if num1<num2:
            x_distance = coordinates[num1,0] - coordinates[num2,0]
            y_distance = coordinates[num1,1] - coordinates[num2,1]
            z_distance = coordinates[num1,2] - coordinates[num2,2]
            distance = numpy.sqrt(x_distance**2 + y_distance**2 + z_distance**2)
            if distance > 0 and distance < 1.5:
                print(F'{symbols[num1]} to {symbols[num2]} : {distance: .3f}')

O to H1 :  0.969
O to H2 :  0.969


## Writing and Using Functions



In [29]:
#def function_name(parameters):
#    **body of your function**
#    **write code using the parameters to calculate something **
#    return value_to_return

In [30]:
def calculate_distance(coords1, coords2):
    x_distance = coords1[0] - coords2[0]
    y_distance = coords1[1] - coords2[1]
    z_distance = coords1[2] - coords2[2]
    distance = numpy.sqrt(x_distance**2 + y_distance**2 + z_distance**2)
    return distance
    

In [31]:
calculate_distance([0, 0, 0], [0, 0, 1])

1.0

In [32]:
calculate_distance([0, 0, 0], [1, 1, 1])

1.7320508075688772

In [33]:
num_atoms = len(symbols)

for num1 in range(0,num_atoms):
     for num2 in range(0, num_atoms):
        #print(num1,num2)
        if num1<num2:
            distance = calculate_distance(coordinates[num1], coordinates[num2])

            if distance > 0 and distance < 1.5:
                print(F'{symbols[num1]} to {symbols[num2]} : {distance: .3f}')

O to H1 :  0.969
O to H2 :  0.969


In [34]:
# Write a function to check and see if a distance is a bond
def bond_check(atom_distance):
    if atom_distance > 0 and atom_distance < 1.5:
        return True
    else:
        return False

In [35]:
bond_check(1.7)

False

In [36]:
bond_check(1.2)

True

In [37]:
bond_check(-50)

False

In [48]:
# Modify the bond check function to take a minimum and a maximum length as an imput
def bond_check(atom_distance, minimum_length=0, maximum_length=1.5):
    """
    Checks if a distance is a bond based on a minimum and a maximum 
    Inputs: distance minimum length for bond, maximum length for bond
    Default: minimum 0 angstroms, maximum:1.5 angstroms
    """
    if atom_distance > minimum_length and atom_distance < maximum_length:
        return True
    else:
        return False

In [49]:
bond_check(1.7,0,2.0)

True

In [50]:
bond_check(1.7)

False

In [51]:
bond_check(1.7, maximum_length=2.0)

True

In [54]:
help(bond_check)

Help on function bond_check in module __main__:

bond_check(atom_distance, minimum_length=0, maximum_length=1.5)
    "
    Checks if a distance is a bond based on a minimum and a maximum 
    Inputs: distance minimum length for bond, maximum length for bond
    Default: minimum 0 angstroms, maximum:1.5 angstroms



In [55]:
for num1 in range(0,num_atoms):
     for num2 in range(0, num_atoms):
        #print(num1,num2)
        if num1<num2:
            distance = calculate_distance(coordinates[num1], coordinates[num2])

            if bond_check(distance) is True:
                print(F'{symbols[num1]} to {symbols[num2]} : {distance: .3f}')

O to H1 :  0.969
O to H2 :  0.969


In [56]:
# Write a new function called open_xyz that opens and process an xyz file. Your function
# should accept a filepath for the input 
def open_xyz(filename):
    """
    This function opens a standard xyz file.
    It returns the symbols as strings and the coordinates as floats
    """
    
    xyz_file = numpy.genfromtxt(fname=filename, skip_header=2, dtype='unicode')
    symbols = xyz_file[:,0]
    coord = xyz_file[:,1 :]
    coord = coord.astype(float)
    return symbols, coord 


In [57]:
import os
import numpy 
def calculate_distance(coords1, coords2):
    x_distance = coords1[0] - coords2[0]
    y_distance = coords1[1] - coords2[1]
    z_distance = coords1[2] - coords2[2]
    distance = numpy.sqrt(x_distance**2 + y_distance**2 + z_distance**2)
    return distance
def bond_check(atom_distance, minimum_length=0, maximum_length=1.5):
    """
    Checks if a distance is a bond based on a minimum and a maximum 
    Inputs: distance minimum length for bond, maximum length for bond
    Default: minimum 0 angstroms, maximum:1.5 angstroms
    """
    if atom_distance > minimum_length and atom_distance < maximum_length:
        return True
    else:
        return False
def open_xyz(filename):
    """
    This function opens a standard xyz file.
    It returns the symbols as strings and the coordinates as floats
    """
    
    xyz_file = numpy.genfromtxt(fname=filename, skip_header=2, dtype='unicode')
    symbols = xyz_file[:,0]
    coord = xyz_file[:,1 :]
    coord = coord.astype(float)
    return symbols, coord 

file_location = os.path.join('data', 'water.xyz')
symbols, coordinates = open_xyz(file_location)
num_atoms = len(symbols)
for num1 in range (0, num_atoms):
    for num2 in range(0, num_atoms):
        if num1<num2:
            distance = calculate_distance(coordinates[num1], coordinates[num2])
            if bond_check(distance) is True:
                print(F'{symbols[num1]} to {symbols[num2]} : {distance: .3f}')


O to H1 :  0.969
O to H2 :  0.969
